# Generated by Django 6.0.5 on 2026-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
